# Generated by Django 5.1.3 on 2024-12-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='img_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='lat',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='lng',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='img_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
