# Generated by Django 5.1.3 on 2024-12-24 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_address_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='app1.address'),
        ),
    ]
