# Generated by Django 5.1.3 on 2025-04-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_address_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='join_date',
            field=models.DateField(null=True),
        ),
    ]
